name: dock_learner
description: "Revised Flutter Project - DockLearner"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^2.27.0
  firebase_auth:
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.3.0
  permission_handler: #^10.0.0
  #  google_sign_in_web:
  googleapis: # ^7.0.0
  url_launcher:
  shared_preferences:
  path_provider: ^2.1.4 # ^2.0.11
  hive: ^2.0.4
  hive_flutter:
  direct_link:
  http:
  youtube_player_flutter: ^9.0.3
  connection_notifier: ^2.0.1
  youtube_player_iframe: ^4.0.4
  youtube:
  percent_indicator:
  flutter_advanced_drawer: ^1.3.6
  #  youtube_downloader: #^0.0.6
  text_marquee:
  page_animation_transition:
  flutter_spinkit: ^5.2.1
  shimmer:
  pdf: ^3.8.0
  share_plus: ^7.0.0
  dropdown_plus: ^0.0.9
  scroll_to_top: ^0.0.5
  flutter_scroll_to_top: ^2.3.0
  widget_zoom: ^0.0.4
  cached_network_image:
  #  flutter_youtube_downloader: #^0.0.5
  #  webview_flutter:
  #  video_player: ^2.1.10
  #  google_mobile_ads: ^0.13.2
  #  share: ^2.0.4
  youtube_explode_dart: ^2.5.1
  dio:
  #  path_provider: ^2.1.1
  #  permission_handler: ^11.0.1
  video_player: ^2.8.1

#  in_app_purchase:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - files/
    - files/images/img.png
    - files/images/youtube_logo.png
    - files/images/firebase_logo.png
    - files/images/app_logo.png
    - files/images/google_logo.png
  fonts:
    - family: SourGummy
      fonts:
        - asset: files/fonts/Parkinsans-VariableFont_wght.ttf

